// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AccountRead
 */
export type AccountRead = {
    /**
     * Connected Accounts
     */
    connected_accounts: Array<ConnectedAccountRead>;
    consents: ConsentRead;
    /**
     * Retention
     */
    retention: 'retain' | 'discard';
};

/**
 * AttributeFindingRead
 *
 * Attribution detail — AttributeRead enriched with candidates + per-item evidence.
 */
export type AttributeFindingRead = {
    /**
     * Art9
     */
    art9?: boolean | null;
    /**
     * Candidates
     */
    candidates: Array<Candidate>;
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Evidence Items
     */
    evidence_items: Array<EvidenceRead>;
    /**
     * Label
     */
    label: string;
    /**
     * Neighborhood
     */
    neighborhood?: string | null;
    /**
     * Precision
     */
    precision?: string | null;
    /**
     * Reasoning
     */
    reasoning: string;
    reliability: Reliability | null;
    /**
     * Sensitive
     */
    sensitive?: boolean | null;
    severity: Severity;
    text_only_reliability?: Reliability | null;
    /**
     * Value
     */
    value: string | null;
};

/**
 * AttributeRead
 *
 * A dashboard attribute card. `null` reliability ⇔ abstain.
 */
export type AttributeRead = {
    /**
     * Abstain
     */
    abstain?: boolean | null;
    /**
     * Art9
     */
    art9?: boolean | null;
    /**
     * Code
     */
    code: string;
    /**
     * Detail
     */
    detail: string | null;
    /**
     * Evidence
     */
    evidence: string;
    /**
     * Evidence Count
     */
    evidence_count?: number | null;
    /**
     * Label
     */
    label: string;
    reliability: Reliability | null;
    /**
     * Sensitive
     */
    sensitive?: boolean | null;
    severity: Severity;
    /**
     * Value
     */
    value: string | null;
};

/**
 * BBox
 */
export type BBox = {
    /**
     * H
     */
    h: number;
    /**
     * W
     */
    w: number;
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
};

/**
 * BenchRow
 */
export type BenchRow = {
    /**
     * Label
     */
    label: string;
    /**
     * Top1
     */
    top1: number;
    /**
     * Top3
     */
    top3: number;
};

/**
 * BenchmarkRead
 */
export type BenchmarkRead = {
    /**
     * Calibration
     */
    calibration: Array<[
        number,
        number
    ]>;
    /**
     * Rows
     */
    rows: Array<BenchRow>;
};

/**
 * Candidate
 */
export type Candidate = {
    /**
     * Label
     */
    label: string;
    /**
     * Note
     */
    note: string;
    /**
     * Rank
     */
    rank: number;
};

/**
 * ConnectedAccountRead
 *
 * Linked account — status + handle only, never tokens.
 */
export type ConnectedAccountRead = {
    /**
     * Handle
     */
    handle?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Platform
     */
    platform: string;
    /**
     * Status
     */
    status: string;
};

/**
 * ConnectorCreate
 */
export type ConnectorCreate = {
    /**
     * Platform
     */
    platform: 'reddit' | 'mastodon' | 'x';
};

/**
 * ConnectorStart
 */
export type ConnectorStart = {
    /**
     * Authorize Url
     */
    authorize_url: string;
};

/**
 * ConsentRead
 */
export type ConsentRead = {
    /**
     * Art9
     */
    art9: boolean;
    /**
     * Decoy
     */
    decoy: boolean;
    /**
     * Purpose
     */
    purpose: boolean;
};

/**
 * ConsentUpdate
 */
export type ConsentUpdate = {
    /**
     * Decoy
     */
    decoy?: boolean;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Special Category
     */
    special_category?: boolean;
};

/**
 * DefendEdit
 */
export type DefendEdit = {
    /**
     * Crop
     */
    crop?: boolean | null;
    /**
     * Date
     */
    date: string;
    /**
     * Decoy
     */
    decoy?: boolean | null;
    /**
     * Exif
     */
    exif?: boolean | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Original
     */
    original?: string | null;
    /**
     * Remove
     */
    remove?: boolean | null;
    /**
     * Segs
     */
    segs?: Array<DiffSeg> | null;
    /**
     * Src
     */
    src: string;
};

/**
 * DefendOptionRead
 *
 * One frontier option; `after` is proven by the held-out adversary (point + interval).
 */
export type DefendOptionRead = {
    after: Reliability;
    /**
     * Desc
     */
    desc: string;
    /**
     * Edits
     */
    edits: Array<DefendEdit>;
    /**
     * Key
     */
    key: 'minimal' | 'stronger' | 'remove' | 'decoy';
    /**
     * Misled
     */
    misled?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Opt In
     */
    opt_in?: boolean | null;
    /**
     * Recommended
     */
    recommended?: boolean | null;
    /**
     * Recovered
     */
    recovered: boolean;
    /**
     * Remove
     */
    remove?: boolean | null;
    /**
     * Truthful
     */
    truthful: boolean;
    /**
     * Utility
     */
    utility: number | null;
    /**
     * Utility Label
     */
    utility_label: string;
};

/**
 * DefendTarget
 */
export type DefendTarget = {
    /**
     * Attribute
     */
    attribute: string;
    before: Reliability;
    /**
     * Value
     */
    value: string;
};

/**
 * DiffSeg
 *
 * A diff segment; `insf` = an inserted falsehood (decoy).
 */
export type DiffSeg = {
    /**
     * T
     */
    t: 'eq' | 'del' | 'ins' | 'insf';
    /**
     * V
     */
    v: string;
};

/**
 * EvalResultRead
 */
export type EvalResultRead = {
    /**
     * Attribute
     */
    attribute: string;
    /**
     * Engine Version
     */
    engine_version: string;
    /**
     * Modality
     */
    modality: string;
    /**
     * Top1
     */
    top1: number;
    /**
     * Top3
     */
    top3: number;
};

/**
 * EvidenceRead
 *
 * One piece of evidence — `proven` (causal ablation) or `likely` (correlational).
 */
export type EvidenceRead = {
    /**
     * Caption
     */
    caption?: string | null;
    /**
     * Citation
     */
    citation?: number | null;
    /**
     * Date
     */
    date: string;
    exif?: Exif | null;
    /**
     * Id
     */
    id: string;
    /**
     * Kind
     */
    kind: 'proven' | 'likely';
    /**
     * Marginal
     */
    marginal?: number | null;
    /**
     * Proxy
     */
    proxy?: number | null;
    /**
     * Rationale
     */
    rationale: string;
    region?: BBox | null;
    /**
     * Source
     */
    source: string;
    /**
     * Spans
     */
    spans?: Array<string> | null;
    /**
     * Text
     */
    text?: string | null;
    /**
     * Type
     */
    type: 'text' | 'photo';
};

/**
 * Exif
 */
export type Exif = {
    /**
     * Device
     */
    device: string;
    /**
     * Gps
     */
    gps: string;
    /**
     * Place
     */
    place: string;
    /**
     * Taken
     */
    taken: string;
};

/**
 * ImportRead
 */
export type ImportRead = {
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Dropped
     */
    dropped?: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Kept
     */
    kept?: number | null;
    /**
     * Platform
     */
    platform?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * InferenceConfirm
 *
 * POST /v1/inferences/{id}/confirm — the user confirms/denies (a live ground-truth signal).
 */
export type InferenceConfirm = {
    /**
     * Confirmed
     */
    confirmed: boolean;
    /**
     * Value
     */
    value: string;
};

/**
 * Problem
 *
 * RFC 9457 problem+json error body (the one error shape across the API).
 */
export type Problem = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Instance
     */
    instance?: string | null;
    /**
     * Status
     */
    status: number;
    /**
     * Title
     */
    title: string;
    /**
     * Type
     */
    type: string;
};

/**
 * Reliability
 *
 * Calibrated reliability — point estimate + interval, 0..1 (the UI renders %).
 */
export type Reliability = {
    /**
     * Hi
     */
    hi: number;
    /**
     * Lo
     */
    lo: number;
    /**
     * Point
     */
    point: number;
};

/**
 * RemediationCreate
 *
 * POST /v1/inferences/{id}/remediations — decoy requires per-use consent.
 */
export type RemediationCreate = {
    /**
     * Decoy
     */
    decoy?: boolean;
    /**
     * Strategy
     */
    strategy?: string | null;
};

/**
 * RemediationRead
 *
 * A proven, advise-only remediation; `within_noise`/`cant_break` are honest non-success.
 */
export type RemediationRead = {
    /**
     * Options
     */
    options: Array<DefendOptionRead>;
    /**
     * Status
     */
    status: 'proven' | 'within_noise' | 'cant_break';
    target: DefendTarget;
};

/**
 * RetentionUpdate
 */
export type RetentionUpdate = {
    /**
     * Retention
     */
    retention: 'retain' | 'discard';
};

/**
 * RunAccepted
 *
 * 202 response — the client polls GET /v1/runs/{id} until terminal.
 */
export type RunAccepted = {
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Status
     */
    status: string;
};

/**
 * RunCreate
 *
 * POST /v1/runs body. `params` is type-specific.
 *
 * Retries are deduped via the `Idempotency-Key` request header (api-design rule), not a field.
 */
export type RunCreate = {
    /**
     * Params
     */
    params?: {
        [key: string]: unknown;
    };
    /**
     * Type
     */
    type: 'attack' | 'eval' | 'remediation';
};

/**
 * RunStatus
 *
 * Poll response for a run.
 */
export type RunStatus = {
    /**
     * Engine Version
     */
    engine_version?: string | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
};

/**
 * Severity
 *
 * Per-persona severity matrix; the UI computes `balanced = max(atrisk, jobseeker)`.
 */
export type Severity = {
    /**
     * Atrisk
     */
    atrisk: 'low' | 'moderate' | 'high' | 'extreme';
    /**
     * Jobseeker
     */
    jobseeker: 'low' | 'moderate' | 'high' | 'extreme';
};

export type HealthzHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzHealthzGetResponses = {
    /**
     * Response Healthz Healthz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthzHealthzGetResponse = HealthzHealthzGetResponses[keyof HealthzHealthzGetResponses];

export type ReadyzReadyzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzReadyzGetResponses = {
    /**
     * Response Readyz Readyz Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type ReadyzReadyzGetResponse = ReadyzReadyzGetResponses[keyof ReadyzReadyzGetResponses];

export type EraseAccountV1AccountDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/account';
};

export type EraseAccountV1AccountDeleteErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type EraseAccountV1AccountDeleteError = EraseAccountV1AccountDeleteErrors[keyof EraseAccountV1AccountDeleteErrors];

export type EraseAccountV1AccountDeleteResponses = {
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type EraseAccountV1AccountDeleteResponse = EraseAccountV1AccountDeleteResponses[keyof EraseAccountV1AccountDeleteResponses];

export type GetAccountV1AccountGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/account';
};

export type GetAccountV1AccountGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type GetAccountV1AccountGetError = GetAccountV1AccountGetErrors[keyof GetAccountV1AccountGetErrors];

export type GetAccountV1AccountGetResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type GetAccountV1AccountGetResponse = GetAccountV1AccountGetResponses[keyof GetAccountV1AccountGetResponses];

export type RevokeConsentV1AccountConsentsDeleteData = {
    body: ConsentUpdate;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/account/consents';
};

export type RevokeConsentV1AccountConsentsDeleteErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type RevokeConsentV1AccountConsentsDeleteError = RevokeConsentV1AccountConsentsDeleteErrors[keyof RevokeConsentV1AccountConsentsDeleteErrors];

export type RevokeConsentV1AccountConsentsDeleteResponses = {
    /**
     * Successful Response
     */
    200: ConsentRead;
};

export type RevokeConsentV1AccountConsentsDeleteResponse = RevokeConsentV1AccountConsentsDeleteResponses[keyof RevokeConsentV1AccountConsentsDeleteResponses];

export type GrantConsentV1AccountConsentsPostData = {
    body: ConsentUpdate;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/account/consents';
};

export type GrantConsentV1AccountConsentsPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type GrantConsentV1AccountConsentsPostError = GrantConsentV1AccountConsentsPostErrors[keyof GrantConsentV1AccountConsentsPostErrors];

export type GrantConsentV1AccountConsentsPostResponses = {
    /**
     * Successful Response
     */
    200: ConsentRead;
};

export type GrantConsentV1AccountConsentsPostResponse = GrantConsentV1AccountConsentsPostResponses[keyof GrantConsentV1AccountConsentsPostResponses];

export type ExportAccountV1AccountExportPostData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/account/export';
};

export type ExportAccountV1AccountExportPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ExportAccountV1AccountExportPostError = ExportAccountV1AccountExportPostErrors[keyof ExportAccountV1AccountExportPostErrors];

export type ExportAccountV1AccountExportPostResponses = {
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type ExportAccountV1AccountExportPostResponse = ExportAccountV1AccountExportPostResponses[keyof ExportAccountV1AccountExportPostResponses];

export type SetRetentionV1AccountRetentionPutData = {
    body: RetentionUpdate;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/account/retention';
};

export type SetRetentionV1AccountRetentionPutErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type SetRetentionV1AccountRetentionPutError = SetRetentionV1AccountRetentionPutErrors[keyof SetRetentionV1AccountRetentionPutErrors];

export type SetRetentionV1AccountRetentionPutResponses = {
    /**
     * Successful Response
     */
    200: AccountRead;
};

export type SetRetentionV1AccountRetentionPutResponse = SetRetentionV1AccountRetentionPutResponses[keyof SetRetentionV1AccountRetentionPutResponses];

export type ListConnectorsV1ConnectorsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors';
};

export type ListConnectorsV1ConnectorsGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ListConnectorsV1ConnectorsGetError = ListConnectorsV1ConnectorsGetErrors[keyof ListConnectorsV1ConnectorsGetErrors];

export type ListConnectorsV1ConnectorsGetResponses = {
    /**
     * Response List Connectors V1 Connectors Get
     *
     * Successful Response
     */
    200: Array<ConnectedAccountRead>;
};

export type ListConnectorsV1ConnectorsGetResponse = ListConnectorsV1ConnectorsGetResponses[keyof ListConnectorsV1ConnectorsGetResponses];

export type StartConnectorV1ConnectorsPostData = {
    body: ConnectorCreate;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors';
};

export type StartConnectorV1ConnectorsPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type StartConnectorV1ConnectorsPostError = StartConnectorV1ConnectorsPostErrors[keyof StartConnectorV1ConnectorsPostErrors];

export type StartConnectorV1ConnectorsPostResponses = {
    /**
     * Successful Response
     */
    200: ConnectorStart;
};

export type StartConnectorV1ConnectorsPostResponse = StartConnectorV1ConnectorsPostResponses[keyof StartConnectorV1ConnectorsPostResponses];

export type ConnectorCallbackV1ConnectorsCallbackGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/connectors/callback';
};

export type ConnectorCallbackV1ConnectorsCallbackGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ConnectorCallbackV1ConnectorsCallbackGetError = ConnectorCallbackV1ConnectorsCallbackGetErrors[keyof ConnectorCallbackV1ConnectorsCallbackGetErrors];

export type ConnectorCallbackV1ConnectorsCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: ConnectedAccountRead;
};

export type ConnectorCallbackV1ConnectorsCallbackGetResponse = ConnectorCallbackV1ConnectorsCallbackGetResponses[keyof ConnectorCallbackV1ConnectorsCallbackGetResponses];

export type RevokeConnectorV1ConnectorsConnectorIdDeleteData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Connector Id
         */
        connector_id: string;
    };
    query?: never;
    url: '/v1/connectors/{connector_id}';
};

export type RevokeConnectorV1ConnectorsConnectorIdDeleteErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type RevokeConnectorV1ConnectorsConnectorIdDeleteError = RevokeConnectorV1ConnectorsConnectorIdDeleteErrors[keyof RevokeConnectorV1ConnectorsConnectorIdDeleteErrors];

export type RevokeConnectorV1ConnectorsConnectorIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type RevokeConnectorV1ConnectorsConnectorIdDeleteResponse = RevokeConnectorV1ConnectorsConnectorIdDeleteResponses[keyof RevokeConnectorV1ConnectorsConnectorIdDeleteResponses];

export type SyncConnectorV1ConnectorsConnectorIdSyncPostData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Connector Id
         */
        connector_id: string;
    };
    query?: never;
    url: '/v1/connectors/{connector_id}/sync';
};

export type SyncConnectorV1ConnectorsConnectorIdSyncPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type SyncConnectorV1ConnectorsConnectorIdSyncPostError = SyncConnectorV1ConnectorsConnectorIdSyncPostErrors[keyof SyncConnectorV1ConnectorsConnectorIdSyncPostErrors];

export type SyncConnectorV1ConnectorsConnectorIdSyncPostResponses = {
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type SyncConnectorV1ConnectorsConnectorIdSyncPostResponse = SyncConnectorV1ConnectorsConnectorIdSyncPostResponses[keyof SyncConnectorV1ConnectorsConnectorIdSyncPostResponses];

export type EvalCalibrationV1EvalCalibrationGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/eval/calibration';
};

export type EvalCalibrationV1EvalCalibrationGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type EvalCalibrationV1EvalCalibrationGetError = EvalCalibrationV1EvalCalibrationGetErrors[keyof EvalCalibrationV1EvalCalibrationGetErrors];

export type EvalCalibrationV1EvalCalibrationGetResponses = {
    /**
     * Successful Response
     */
    200: BenchmarkRead;
};

export type EvalCalibrationV1EvalCalibrationGetResponse = EvalCalibrationV1EvalCalibrationGetResponses[keyof EvalCalibrationV1EvalCalibrationGetResponses];

export type EvalResultsV1EvalResultsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/eval/results';
};

export type EvalResultsV1EvalResultsGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type EvalResultsV1EvalResultsGetError = EvalResultsV1EvalResultsGetErrors[keyof EvalResultsV1EvalResultsGetErrors];

export type EvalResultsV1EvalResultsGetResponses = {
    /**
     * Response Eval Results V1 Eval Results Get
     *
     * Successful Response
     */
    200: Array<EvalResultRead>;
};

export type EvalResultsV1EvalResultsGetResponse = EvalResultsV1EvalResultsGetResponses[keyof EvalResultsV1EvalResultsGetResponses];

export type ListImportsV1ImportsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/imports';
};

export type ListImportsV1ImportsGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ListImportsV1ImportsGetError = ListImportsV1ImportsGetErrors[keyof ListImportsV1ImportsGetErrors];

export type ListImportsV1ImportsGetResponses = {
    /**
     * Response List Imports V1 Imports Get
     *
     * Successful Response
     */
    200: Array<ImportRead>;
};

export type ListImportsV1ImportsGetResponse = ListImportsV1ImportsGetResponses[keyof ListImportsV1ImportsGetResponses];

export type CreateImportV1ImportsPostData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/imports';
};

export type CreateImportV1ImportsPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type CreateImportV1ImportsPostError = CreateImportV1ImportsPostErrors[keyof CreateImportV1ImportsPostErrors];

export type CreateImportV1ImportsPostResponses = {
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type CreateImportV1ImportsPostResponse = CreateImportV1ImportsPostResponses[keyof CreateImportV1ImportsPostResponses];

export type GetImportV1ImportsImportIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Import Id
         */
        import_id: string;
    };
    query?: never;
    url: '/v1/imports/{import_id}';
};

export type GetImportV1ImportsImportIdGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type GetImportV1ImportsImportIdGetError = GetImportV1ImportsImportIdGetErrors[keyof GetImportV1ImportsImportIdGetErrors];

export type GetImportV1ImportsImportIdGetResponses = {
    /**
     * Successful Response
     */
    200: ImportRead;
};

export type GetImportV1ImportsImportIdGetResponse = GetImportV1ImportsImportIdGetResponses[keyof GetImportV1ImportsImportIdGetResponses];

export type ListInferencesV1InferencesGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Run Id
         */
        run_id?: string | null;
        /**
         * Profile Id
         */
        profile_id?: string | null;
    };
    url: '/v1/inferences';
};

export type ListInferencesV1InferencesGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ListInferencesV1InferencesGetError = ListInferencesV1InferencesGetErrors[keyof ListInferencesV1InferencesGetErrors];

export type ListInferencesV1InferencesGetResponses = {
    /**
     * Response List Inferences V1 Inferences Get
     *
     * Successful Response
     */
    200: Array<AttributeRead>;
};

export type ListInferencesV1InferencesGetResponse = ListInferencesV1InferencesGetResponses[keyof ListInferencesV1InferencesGetResponses];

export type GetInferenceV1InferencesInferenceIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Inference Id
         */
        inference_id: string;
    };
    query?: never;
    url: '/v1/inferences/{inference_id}';
};

export type GetInferenceV1InferencesInferenceIdGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type GetInferenceV1InferencesInferenceIdGetError = GetInferenceV1InferencesInferenceIdGetErrors[keyof GetInferenceV1InferencesInferenceIdGetErrors];

export type GetInferenceV1InferencesInferenceIdGetResponses = {
    /**
     * Successful Response
     */
    200: AttributeFindingRead;
};

export type GetInferenceV1InferencesInferenceIdGetResponse = GetInferenceV1InferencesInferenceIdGetResponses[keyof GetInferenceV1InferencesInferenceIdGetResponses];

export type ConfirmInferenceV1InferencesInferenceIdConfirmPostData = {
    body: InferenceConfirm;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Inference Id
         */
        inference_id: string;
    };
    query?: never;
    url: '/v1/inferences/{inference_id}/confirm';
};

export type ConfirmInferenceV1InferencesInferenceIdConfirmPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ConfirmInferenceV1InferencesInferenceIdConfirmPostError = ConfirmInferenceV1InferencesInferenceIdConfirmPostErrors[keyof ConfirmInferenceV1InferencesInferenceIdConfirmPostErrors];

export type ConfirmInferenceV1InferencesInferenceIdConfirmPostResponses = {
    /**
     * Successful Response
     */
    200: AttributeFindingRead;
};

export type ConfirmInferenceV1InferencesInferenceIdConfirmPostResponse = ConfirmInferenceV1InferencesInferenceIdConfirmPostResponses[keyof ConfirmInferenceV1InferencesInferenceIdConfirmPostResponses];

export type CreateRemediationV1InferencesInferenceIdRemediationsPostData = {
    body: RemediationCreate;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Inference Id
         */
        inference_id: string;
    };
    query?: never;
    url: '/v1/inferences/{inference_id}/remediations';
};

export type CreateRemediationV1InferencesInferenceIdRemediationsPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type CreateRemediationV1InferencesInferenceIdRemediationsPostError = CreateRemediationV1InferencesInferenceIdRemediationsPostErrors[keyof CreateRemediationV1InferencesInferenceIdRemediationsPostErrors];

export type CreateRemediationV1InferencesInferenceIdRemediationsPostResponses = {
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type CreateRemediationV1InferencesInferenceIdRemediationsPostResponse = CreateRemediationV1InferencesInferenceIdRemediationsPostResponses[keyof CreateRemediationV1InferencesInferenceIdRemediationsPostResponses];

export type ListRemediationsV1RemediationsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: {
        /**
         * Inference Id
         */
        inference_id?: string | null;
    };
    url: '/v1/remediations';
};

export type ListRemediationsV1RemediationsGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ListRemediationsV1RemediationsGetError = ListRemediationsV1RemediationsGetErrors[keyof ListRemediationsV1RemediationsGetErrors];

export type ListRemediationsV1RemediationsGetResponses = {
    /**
     * Response List Remediations V1 Remediations Get
     *
     * Successful Response
     */
    200: Array<RemediationRead>;
};

export type ListRemediationsV1RemediationsGetResponse = ListRemediationsV1RemediationsGetResponses[keyof ListRemediationsV1RemediationsGetResponses];

export type GetRemediationV1RemediationsRemediationIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Remediation Id
         */
        remediation_id: string;
    };
    query?: never;
    url: '/v1/remediations/{remediation_id}';
};

export type GetRemediationV1RemediationsRemediationIdGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type GetRemediationV1RemediationsRemediationIdGetError = GetRemediationV1RemediationsRemediationIdGetErrors[keyof GetRemediationV1RemediationsRemediationIdGetErrors];

export type GetRemediationV1RemediationsRemediationIdGetResponses = {
    /**
     * Successful Response
     */
    200: RemediationRead;
};

export type GetRemediationV1RemediationsRemediationIdGetResponse = GetRemediationV1RemediationsRemediationIdGetResponses[keyof GetRemediationV1RemediationsRemediationIdGetResponses];

export type ListRunsV1RunsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/runs';
};

export type ListRunsV1RunsGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ListRunsV1RunsGetError = ListRunsV1RunsGetErrors[keyof ListRunsV1RunsGetErrors];

export type ListRunsV1RunsGetResponses = {
    /**
     * Response List Runs V1 Runs Get
     *
     * Successful Response
     */
    200: Array<RunStatus>;
};

export type ListRunsV1RunsGetResponse = ListRunsV1RunsGetResponses[keyof ListRunsV1RunsGetResponses];

export type CreateRunV1RunsPostData = {
    body: RunCreate;
    headers?: {
        /**
         * Idempotency-Key
         */
        'idempotency-key'?: string | null;
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/v1/runs';
};

export type CreateRunV1RunsPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type CreateRunV1RunsPostError = CreateRunV1RunsPostErrors[keyof CreateRunV1RunsPostErrors];

export type CreateRunV1RunsPostResponses = {
    /**
     * Successful Response
     */
    202: RunAccepted;
};

export type CreateRunV1RunsPostResponse = CreateRunV1RunsPostResponses[keyof CreateRunV1RunsPostResponses];

export type ReadRunV1RunsRunIdGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/runs/{run_id}';
};

export type ReadRunV1RunsRunIdGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ReadRunV1RunsRunIdGetError = ReadRunV1RunsRunIdGetErrors[keyof ReadRunV1RunsRunIdGetErrors];

export type ReadRunV1RunsRunIdGetResponses = {
    /**
     * Successful Response
     */
    200: RunStatus;
};

export type ReadRunV1RunsRunIdGetResponse = ReadRunV1RunsRunIdGetResponses[keyof ReadRunV1RunsRunIdGetResponses];

export type RunEventsV1RunsRunIdEventsGetData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/runs/{run_id}/events';
};

export type RunEventsV1RunsRunIdEventsGetErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type RunEventsV1RunsRunIdEventsGetError = RunEventsV1RunsRunIdEventsGetErrors[keyof RunEventsV1RunsRunIdEventsGetErrors];

export type RunEventsV1RunsRunIdEventsGetResponses = {
    /**
     * SSE stream of run status
     */
    200: unknown;
};

export type CancelRunV1RunsRunIdCancelPostData = {
    body?: never;
    headers?: {
        /**
         * X-Dev-User-Id
         */
        'x-dev-user-id'?: string | null;
    };
    path: {
        /**
         * Run Id
         */
        run_id: string;
    };
    query?: never;
    url: '/v1/runs/{run_id}:cancel';
};

export type CancelRunV1RunsRunIdCancelPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type CancelRunV1RunsRunIdCancelPostError = CancelRunV1RunsRunIdCancelPostErrors[keyof CancelRunV1RunsRunIdCancelPostErrors];

export type CancelRunV1RunsRunIdCancelPostResponses = {
    /**
     * Successful Response
     */
    202: RunStatus;
};

export type CancelRunV1RunsRunIdCancelPostResponse = CancelRunV1RunsRunIdCancelPostResponses[keyof CancelRunV1RunsRunIdCancelPostResponses];

export type ClerkWebhookWebhooksClerkPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/webhooks/clerk';
};

export type ClerkWebhookWebhooksClerkPostErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Not Implemented
     */
    501: Problem;
};

export type ClerkWebhookWebhooksClerkPostError = ClerkWebhookWebhooksClerkPostErrors[keyof ClerkWebhookWebhooksClerkPostErrors];

export type ClerkWebhookWebhooksClerkPostResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type ClerkWebhookWebhooksClerkPostResponse = ClerkWebhookWebhooksClerkPostResponses[keyof ClerkWebhookWebhooksClerkPostResponses];
