// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * BBox
 */
export const zBBox = z.object({
    h: z.number(),
    w: z.number(),
    x: z.number(),
    y: z.number()
});

/**
 * BenchRow
 */
export const zBenchRow = z.object({
    label: z.string(),
    top1: z.number(),
    top3: z.number()
});

/**
 * BenchmarkRead
 */
export const zBenchmarkRead = z.object({
    calibration: z.array(z.tuple([z.number(), z.number()])),
    rows: z.array(zBenchRow)
});

/**
 * Candidate
 */
export const zCandidate = z.object({
    label: z.string(),
    note: z.string(),
    rank: z.int()
});

/**
 * ConnectedAccountRead
 *
 * Linked account — status + handle only, never tokens.
 */
export const zConnectedAccountRead = z.object({
    handle: z.string().nullish(),
    id: z.uuid(),
    platform: z.string(),
    status: z.string()
});

/**
 * ConnectorCreate
 */
export const zConnectorCreate = z.object({
    platform: z.enum([
        'reddit',
        'mastodon',
        'x'
    ])
});

/**
 * ConnectorStart
 */
export const zConnectorStart = z.object({
    authorize_url: z.string()
});

/**
 * ConsentRead
 */
export const zConsentRead = z.object({
    art9: z.boolean(),
    decoy: z.boolean(),
    purpose: z.boolean()
});

/**
 * AccountRead
 */
export const zAccountRead = z.object({
    connected_accounts: z.array(zConnectedAccountRead),
    consents: zConsentRead,
    retention: z.enum(['retain', 'discard'])
});

/**
 * ConsentUpdate
 */
export const zConsentUpdate = z.object({
    decoy: z.boolean().optional().default(false),
    purpose: z.string(),
    special_category: z.boolean().optional().default(false)
});

/**
 * DiffSeg
 *
 * A diff segment; `insf` = an inserted falsehood (decoy).
 */
export const zDiffSeg = z.object({
    t: z.enum([
        'eq',
        'del',
        'ins',
        'insf'
    ]),
    v: z.string()
});

/**
 * DefendEdit
 */
export const zDefendEdit = z.object({
    crop: z.boolean().nullish(),
    date: z.string(),
    decoy: z.boolean().nullish(),
    exif: z.boolean().nullish(),
    note: z.string().nullish(),
    original: z.string().nullish(),
    remove: z.boolean().nullish(),
    segs: z.array(zDiffSeg).nullish(),
    src: z.string()
});

/**
 * EvalResultRead
 */
export const zEvalResultRead = z.object({
    attribute: z.string(),
    engine_version: z.string(),
    modality: z.string(),
    top1: z.number(),
    top3: z.number()
});

/**
 * Exif
 */
export const zExif = z.object({
    device: z.string(),
    gps: z.string(),
    place: z.string(),
    taken: z.string()
});

/**
 * EvidenceRead
 *
 * One piece of evidence — `proven` (causal ablation) or `likely` (correlational).
 */
export const zEvidenceRead = z.object({
    caption: z.string().nullish(),
    citation: z.number().nullish(),
    date: z.string(),
    exif: zExif.nullish(),
    id: z.string(),
    kind: z.enum(['proven', 'likely']),
    marginal: z.number().nullish(),
    proxy: z.number().nullish(),
    rationale: z.string(),
    region: zBBox.nullish(),
    source: z.string(),
    spans: z.array(z.string()).nullish(),
    text: z.string().nullish(),
    type: z.enum(['text', 'photo'])
});

/**
 * ImportRead
 */
export const zImportRead = z.object({
    created_at: z.iso.datetime().nullish(),
    dropped: z.int().nullish(),
    id: z.uuid(),
    kept: z.int().nullish(),
    platform: z.string().nullish(),
    status: z.string()
});

/**
 * InferenceConfirm
 *
 * POST /v1/inferences/{id}/confirm — the user confirms/denies (a live ground-truth signal).
 */
export const zInferenceConfirm = z.object({
    confirmed: z.boolean(),
    value: z.string()
});

/**
 * Problem
 *
 * RFC 9457 problem+json error body (the one error shape across the API).
 */
export const zProblem = z.object({
    detail: z.string().nullish(),
    instance: z.string().nullish(),
    status: z.int(),
    title: z.string(),
    type: z.string()
});

/**
 * Reliability
 *
 * Calibrated reliability — point estimate + interval, 0..1 (the UI renders %).
 */
export const zReliability = z.object({
    hi: z.number(),
    lo: z.number(),
    point: z.number()
});

/**
 * DefendOptionRead
 *
 * One frontier option; `after` is proven by the held-out adversary (point + interval).
 */
export const zDefendOptionRead = z.object({
    after: zReliability,
    desc: z.string(),
    edits: z.array(zDefendEdit),
    key: z.enum([
        'minimal',
        'stronger',
        'remove',
        'decoy'
    ]),
    misled: z.string().nullish(),
    name: z.string(),
    opt_in: z.boolean().nullish(),
    recommended: z.boolean().nullish(),
    recovered: z.boolean(),
    remove: z.boolean().nullish(),
    truthful: z.boolean(),
    utility: z.int().nullable(),
    utility_label: z.string()
});

/**
 * DefendTarget
 */
export const zDefendTarget = z.object({
    attribute: z.string(),
    before: zReliability,
    value: z.string()
});

/**
 * RemediationCreate
 *
 * POST /v1/inferences/{id}/remediations — decoy requires per-use consent.
 */
export const zRemediationCreate = z.object({
    decoy: z.boolean().optional().default(false),
    strategy: z.string().nullish()
});

/**
 * RemediationRead
 *
 * A proven, advise-only remediation; `within_noise`/`cant_break` are honest non-success.
 */
export const zRemediationRead = z.object({
    options: z.array(zDefendOptionRead),
    status: z.enum([
        'proven',
        'within_noise',
        'cant_break'
    ]),
    target: zDefendTarget
});

/**
 * RetentionUpdate
 */
export const zRetentionUpdate = z.object({
    retention: z.enum(['retain', 'discard'])
});

/**
 * RunAccepted
 *
 * 202 response — the client polls GET /v1/runs/{id} until terminal.
 */
export const zRunAccepted = z.object({
    run_id: z.uuid(),
    status: z.string()
});

/**
 * RunCreate
 *
 * POST /v1/runs body. `params` is type-specific.
 *
 * Retries are deduped via the `Idempotency-Key` request header (api-design rule), not a field.
 */
export const zRunCreate = z.object({
    params: z.record(z.string(), z.unknown()).optional().default({}),
    type: z.enum([
        'attack',
        'eval',
        'remediation'
    ])
});

/**
 * RunStatus
 *
 * Poll response for a run.
 */
export const zRunStatus = z.object({
    engine_version: z.string().nullish(),
    error: z.string().nullish(),
    id: z.uuid(),
    status: z.string(),
    type: z.string()
});

/**
 * Severity
 *
 * Per-persona severity matrix; the UI computes `balanced = max(atrisk, jobseeker)`.
 */
export const zSeverity = z.object({
    atrisk: z.enum([
        'low',
        'moderate',
        'high',
        'extreme'
    ]),
    jobseeker: z.enum([
        'low',
        'moderate',
        'high',
        'extreme'
    ])
});

/**
 * AttributeFindingRead
 *
 * Attribution detail — AttributeRead enriched with candidates + per-item evidence.
 */
export const zAttributeFindingRead = z.object({
    art9: z.boolean().nullish(),
    candidates: z.array(zCandidate),
    code: z.string(),
    detail: z.string().nullish(),
    evidence_items: z.array(zEvidenceRead),
    label: z.string(),
    neighborhood: z.string().nullish(),
    precision: z.string().nullish(),
    reasoning: z.string(),
    reliability: zReliability.nullable(),
    sensitive: z.boolean().nullish(),
    severity: zSeverity,
    text_only_reliability: zReliability.nullish(),
    value: z.string().nullable()
});

/**
 * AttributeRead
 *
 * A dashboard attribute card. `null` reliability ⇔ abstain.
 */
export const zAttributeRead = z.object({
    abstain: z.boolean().nullish(),
    art9: z.boolean().nullish(),
    code: z.string(),
    detail: z.string().nullable(),
    evidence: z.string(),
    evidence_count: z.int().nullish(),
    label: z.string(),
    reliability: zReliability.nullable(),
    sensitive: z.boolean().nullish(),
    severity: zSeverity,
    value: z.string().nullable()
});

/**
 * Response Healthz Healthz Get
 *
 * Successful Response
 */
export const zHealthzHealthzGetResponse = z.record(z.string(), z.string());

/**
 * Response Readyz Readyz Get
 *
 * Successful Response
 */
export const zReadyzReadyzGetResponse = z.record(z.string(), z.string());

export const zEraseAccountV1AccountDeleteHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zEraseAccountV1AccountDeleteResponse = zRunAccepted;

export const zGetAccountV1AccountGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zGetAccountV1AccountGetResponse = zAccountRead;

export const zRevokeConsentV1AccountConsentsDeleteBody = zConsentUpdate;

export const zRevokeConsentV1AccountConsentsDeleteHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zRevokeConsentV1AccountConsentsDeleteResponse = zConsentRead;

export const zGrantConsentV1AccountConsentsPostBody = zConsentUpdate;

export const zGrantConsentV1AccountConsentsPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zGrantConsentV1AccountConsentsPostResponse = zConsentRead;

export const zExportAccountV1AccountExportPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zExportAccountV1AccountExportPostResponse = zRunAccepted;

export const zSetRetentionV1AccountRetentionPutBody = zRetentionUpdate;

export const zSetRetentionV1AccountRetentionPutHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zSetRetentionV1AccountRetentionPutResponse = zAccountRead;

export const zListConnectorsV1ConnectorsGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Response List Connectors V1 Connectors Get
 *
 * Successful Response
 */
export const zListConnectorsV1ConnectorsGetResponse = z.array(zConnectedAccountRead);

export const zStartConnectorV1ConnectorsPostBody = zConnectorCreate;

export const zStartConnectorV1ConnectorsPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zStartConnectorV1ConnectorsPostResponse = zConnectorStart;

export const zConnectorCallbackV1ConnectorsCallbackGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zConnectorCallbackV1ConnectorsCallbackGetResponse = zConnectedAccountRead;

export const zRevokeConnectorV1ConnectorsConnectorIdDeleteHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zRevokeConnectorV1ConnectorsConnectorIdDeletePath = z.object({
    connector_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeConnectorV1ConnectorsConnectorIdDeleteResponse = z.void();

export const zSyncConnectorV1ConnectorsConnectorIdSyncPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zSyncConnectorV1ConnectorsConnectorIdSyncPostPath = z.object({
    connector_id: z.uuid()
});

/**
 * Successful Response
 */
export const zSyncConnectorV1ConnectorsConnectorIdSyncPostResponse = zRunAccepted;

/**
 * Successful Response
 */
export const zEvalCalibrationV1EvalCalibrationGetResponse = zBenchmarkRead;

/**
 * Response Eval Results V1 Eval Results Get
 *
 * Successful Response
 */
export const zEvalResultsV1EvalResultsGetResponse = z.array(zEvalResultRead);

export const zListImportsV1ImportsGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Response List Imports V1 Imports Get
 *
 * Successful Response
 */
export const zListImportsV1ImportsGetResponse = z.array(zImportRead);

export const zCreateImportV1ImportsPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zCreateImportV1ImportsPostResponse = zRunAccepted;

export const zGetImportV1ImportsImportIdGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zGetImportV1ImportsImportIdGetPath = z.object({
    import_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetImportV1ImportsImportIdGetResponse = zImportRead;

export const zListInferencesV1InferencesGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zListInferencesV1InferencesGetQuery = z.object({
    run_id: z.uuid().nullish(),
    profile_id: z.uuid().nullish()
});

/**
 * Response List Inferences V1 Inferences Get
 *
 * Successful Response
 */
export const zListInferencesV1InferencesGetResponse = z.array(zAttributeRead);

export const zGetInferenceV1InferencesInferenceIdGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zGetInferenceV1InferencesInferenceIdGetPath = z.object({
    inference_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetInferenceV1InferencesInferenceIdGetResponse = zAttributeFindingRead;

export const zConfirmInferenceV1InferencesInferenceIdConfirmPostBody = zInferenceConfirm;

export const zConfirmInferenceV1InferencesInferenceIdConfirmPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zConfirmInferenceV1InferencesInferenceIdConfirmPostPath = z.object({
    inference_id: z.uuid()
});

/**
 * Successful Response
 */
export const zConfirmInferenceV1InferencesInferenceIdConfirmPostResponse = zAttributeFindingRead;

export const zCreateRemediationV1InferencesInferenceIdRemediationsPostBody = zRemediationCreate;

export const zCreateRemediationV1InferencesInferenceIdRemediationsPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zCreateRemediationV1InferencesInferenceIdRemediationsPostPath = z.object({
    inference_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateRemediationV1InferencesInferenceIdRemediationsPostResponse = zRunAccepted;

export const zListRemediationsV1RemediationsGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zListRemediationsV1RemediationsGetQuery = z.object({
    inference_id: z.uuid().nullish()
});

/**
 * Response List Remediations V1 Remediations Get
 *
 * Successful Response
 */
export const zListRemediationsV1RemediationsGetResponse = z.array(zRemediationRead);

export const zGetRemediationV1RemediationsRemediationIdGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zGetRemediationV1RemediationsRemediationIdGetPath = z.object({
    remediation_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetRemediationV1RemediationsRemediationIdGetResponse = zRemediationRead;

export const zListRunsV1RunsGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Response List Runs V1 Runs Get
 *
 * Successful Response
 */
export const zListRunsV1RunsGetResponse = z.array(zRunStatus);

export const zCreateRunV1RunsPostBody = zRunCreate;

export const zCreateRunV1RunsPostHeaders = z.object({
    'idempotency-key': z.string().nullish(),
    'x-dev-user-id': z.uuid().nullish()
});

/**
 * Successful Response
 */
export const zCreateRunV1RunsPostResponse = zRunAccepted;

export const zReadRunV1RunsRunIdGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zReadRunV1RunsRunIdGetPath = z.object({
    run_id: z.uuid()
});

/**
 * Successful Response
 */
export const zReadRunV1RunsRunIdGetResponse = zRunStatus;

export const zRunEventsV1RunsRunIdEventsGetHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zRunEventsV1RunsRunIdEventsGetPath = z.object({
    run_id: z.uuid()
});

export const zCancelRunV1RunsRunIdCancelPostHeaders = z.object({
    'x-dev-user-id': z.uuid().nullish()
});

export const zCancelRunV1RunsRunIdCancelPostPath = z.object({
    run_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCancelRunV1RunsRunIdCancelPostResponse = zRunStatus;

/**
 * Successful Response
 */
export const zClerkWebhookWebhooksClerkPostResponse = z.void();
