import {
  ArrowRight,
  ArrowLeft,
  User,
  Link,
  Download,
  LogOut,
  Scan,
  Sun,
  Moon,
  Check,
  Inbox,
  WifiOff,
  RotateCw,
  ChevronRight,
  ShieldCheck,
  CircleAlert,
  TriangleAlert,
  OctagonAlert,
  CircleMinus,
  Crosshair,
  Gauge,
  Shield,
  Upload,
  MessageSquare,
  AtSign,
  Archive,
  Package,
  Image as ImageGlyph,
  Lock,
  Trash2,
  Info,
  X,
  Plus,
  FileText,
  MapPin,
  ShieldAlert,
  Copy,
  LifeBuoy,
  Key,
  ExternalLink,
  BarChart3,
  Users,
  type LucideIcon,
} from "lucide-react";

/**
 * Curated kebab-name → Lucide component map. Kept explicit (not the full Lucide set)
 * so the bundle stays tight and `IconName` is type-checked. Extend per screen as new
 * icons are needed.
 */
export const ICONS = {
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
  user: User,
  link: Link,
  download: Download,
  "log-out": LogOut,
  scan: Scan,
  sun: Sun,
  moon: Moon,
  check: Check,
  inbox: Inbox,
  "wifi-off": WifiOff,
  "rotate-cw": RotateCw,
  "chevron-right": ChevronRight,
  "shield-check": ShieldCheck,
  "circle-alert": CircleAlert,
  "triangle-alert": TriangleAlert,
  "octagon-alert": OctagonAlert,
  "circle-minus": CircleMinus,
  crosshair: Crosshair,
  gauge: Gauge,
  shield: Shield,
  upload: Upload,
  "message-square": MessageSquare,
  "at-sign": AtSign,
  archive: Archive,
  package: Package,
  image: ImageGlyph,
  lock: Lock,
  "trash-2": Trash2,
  info: Info,
  x: X,
  plus: Plus,
  "file-text": FileText,
  "map-pin": MapPin,
  "shield-alert": ShieldAlert,
  copy: Copy,
  "life-buoy": LifeBuoy,
  key: Key,
  "external-link": ExternalLink,
  "bar-chart-3": BarChart3,
  users: Users,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
